Fix macro (#1)
Fixes ` error: redefinition of 'defer_object___COUNTER__'`
if two DEFER were used in the same function and also
`warning: unused variable 'defer_object___COUNTER__' `.